# Generated by Django 4.0.4 on 2022-05-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_pessoa_pf_pj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pf',
            options={'verbose_name': 'Pessoa Física', 'verbose_name_plural': 'Pessoas Físicas'},
        ),
        migrations.AlterModelOptions(
            name='pj',
            options={'verbose_name': 'Pessoa Jurídica', 'verbose_name_plural': 'Pessoas Jurídicas'},
        ),
    ]
