# Generated by Django 4.0.4 on 2022-05-24 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_pf_options_alter_pj_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pj',
            name='ie',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='inscrição estadual'),
        ),
    ]
