# Generated by Django 4.0 on 2021-12-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_movie_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='create_date',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
