# Generated by Django 4.0 on 2021-12-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='título')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='lançamento')),
            ],
            options={
                'verbose_name': 'filme',
                'verbose_name_plural': 'filmes',
                'ordering': ('id',),
            },
        ),
    ]
